### ISSUE TITLE
data and performance problem

### ISSUE THREAD

**Issue by fighting41love** [GaoQ1/NER_medical_records#2]
Thanks for sharing the code.
Questions:
1. what is the training data?
2. do you compare the NER of deep learning with NER in jieba or Hannlp ? 
3. what is the key factor in identifying the performance of NER models?
Thanks!

**Comment by GaoQ1** [comment]
1. Training data is the Electronic Medical Record, you can find in assert/raw_corpus/origin_data/intent/..txt
2. I have not compare the difference betwen jieba and Hannlp
3. The key factor I thought is the dataset

**Comment by fighting41love** [comment]
Thanks for your response. Thanks!
