### ISSUE TITLE
what we suppose to do?

### ISSUE THREAD

**Issue by SeekPoint** [GaoQ1/NER_medical_records#5]
ub16c9@ub16c9-gpu:~/ub16_prj/ner-slot_filling$ python3.6 train_evaluate.py --clean True --train True --model_type bilstm
Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.669 seconds.
Prefix dict has been built succesfully.
开始训练模型！！！
14253it [00:00, 291884.34it/s]
Python 3.6.8 (default, Dec 24 2018, 19:24:27) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> 
>>> 
>>>

**Comment by GaoQ1** [comment]
估计是因为你打开了`code.interact(local=locals())`这个是调试命令

**Comment by SeekPoint** [comment]
got it:

    if len(sentence) > 0:
        if 'DOCSTART' not in sentence[0][0]:
            sentences.append(sentence)

    code.interact(local=locals())

    return sentences
